version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    env_file:
      - .env
    environment:
      - CHROMA_HOST=3.6.132.24
      - CHROMA_PORT=8000
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    networks:
      - buddhi-network

networks:
  buddhi-network:
    driver: bridge
